" Enable syntax and filetype plugins
	syntax on
	filetype plugin indent on

" Hide buffers when abandoned
	set hidden

" Backspace
	set backspace=indent,eol,start

" Timeout
	set ttimeout
	set ttimeoutlen=100

" Incremental search
	set incsearch

" Enhanced command mode tab completion
	set wildmenu

" Scrolloff
	set scrolloff=1
	set sidescrolloff=5

" Comments
	set formatoptions+=j formatoptions-=cro

" Automatically reead files changed outside of Vim
	set autoread

" Extended matching with %
	packadd matchit

" Change viminfo location
	set viminfo+=n~/.vim/viminfo

" Use colors that look good on a dark background
	set background=dark

" Enable line wrapping
	set wrap

" Populate airline fonts
	let g:airline_powerline_fonts = 1

" display line number of current line and relative line numbers
	set number relativenumber

" Indentation
	set autoindent smartindent
	set tabstop=4
	set softtabstop=4
	set shiftwidth=4
	set noexpandtab

" Ignore case in lowercase searches
	set ignorecase
	set smartcase

" Split to the bottom and the right
	set splitbelow splitright

" Temporary fix for relative line number being underlined
" https://github.com/vim/vim/issues/5017
	set cursorlineopt=line

" Update diff when a buffer is written
	autocmd BufWritePost * if &diff == 1 | diffupdate | endif

" Always display status line
	set laststatus=2

" vim_better_whitespace settings
	let g:strip_whitelines_at_eof=1
	let g:show_spaces_that_precede_tabs=1

" Change <Leader> to <Space>
	let mapleader = " "
	nnoremap <Space> <Nop>

" Replace all mapping
	nnoremap	<Leader>r	:%s/\v/g<Left><Left>

" fzf mappings
	nnoremap	<Leader>f	:Files<Enter>
	nnoremap	<Leader>l	:Lines<Enter>
	nnoremap	<leader>b	:Buffers<Enter>
	nnoremap	<leader>h	:Helptags<Enter>
