#!/usr/bin/env sh

BATTERY="/sys/class/power_supply/BAT0"

[ -e ${BATTERY} ] || exit 33

STATUS=$(cat "${BATTERY}/status")
CAPACITY=$(cat "${BATTERY}/capacity")

case ${STATUS} in
	Discharging)
		if [ ${CAPACITY} -lt 5 ] ; then
			exit 33
		elif [ ${CAPACITY} -lt 10 ] ; then
			ICON=" "
			COLOR="#FF0000"
		elif [ ${CAPACITY} -lt 25 ] ; then
			ICON=" "
			COLOR="#FFAE00"
		elif [ ${CAPACITY} -lt 50 ] ; then
			ICON=" "
		elif [ ${CAPACITY} -lt 75 ] ; then
			ICON=" "
		else
			ICON=" "
		fi
		;;
	Full|Charging)
		ICON=""
		;;
esac

echo "${ICON} ${CAPACITY}%"
echo "${ICON} ${CAPACITY}%"
echo "${COLOR}"

exit 0
