#!/usr/bin/env sh

TYPE=$(nmcli -t -f TYPE connection show --active)
NAME=$(nmcli -t -f NAME connection show --active)

[ -z "${TYPE}" ] && exit 33

case "${TYPE}" in
	vpn*)
		ICON=" "
		;;
	*ethernet*)
		ICON=" "
		;;
	*wireless)
		ICON=" "
		;;
esac

echo "${ICON} ${NAME}"

case $BLOCK_BUTTON in
	1)
		$TERMINAL -e nmtui
		;;
esac

exit 0
