#!/usr/bin/env sh

TYPE=$(nmcli -t -f TYPE connection show --active)
NAME=$(nmcli -t -f NAME connection show --active)

case "${TYPE}" in
	vpn*)
		ICON=" "
		;;
	*ethernet*)
		ICON=" "
		;;
	*wireless)
		ICON=" "
		;;
	*)
		ICON=" "
		NAME="No connection"
		COLOR="#FF0000"
		;;
esac

echo "${ICON} ${NAME}"
echo "${ICON} ${NAME}"
echo "${COLOR}"

case $BLOCK_BUTTON in
	1)
		termite -e nmtui-connect --class=floating
		;;
esac

exit 0
