#!/usr/bin/env sh

TYPE=$(nmcli -t -f TYPE connection show --active)
NAME=$(nmcli -t -f NAME connection show --active)

[ -z ${TYPE} ] && exit 33

case ${TYPE} in
	*ethernet*)
		ICON=" "
		;;
	*wireless)
		ICON=" "
		;;
esac

echo "${ICON} ${NAME}"
echo "${ICON} ${NAME}"
echo ""

case $BLOCK_BUTTON in
	1)
		$TERMINAL -e nmtui
		;;
esac

exit 0
