#!/usr/bin/env sh

VOLUME=`pulsemixer --get-volume | cut -d " " -f1`%
MUTED=`pulsemixer --get-mute`

case $MUTED in
	0)
		ICON=" "
		;;
	1)
		ICON=" "
		;;
esac

echo "${ICON} ${VOLUME}"
echo "${ICON} ${VOLUME}"
echo "${COLOR}"

case $BLOCK_BUTTON  in
	1)
		termite -e pulsemixer --class=floating
		;;
esac

exit 0
